### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by SwxtchCode** [ejrv/VPNs#14]
Hola VPN isn't in here?

**Comment by jxsl13** [comment]
What?

**Comment by LifeIsNull** [comment]
This website I moderate has this problem with one stupid spammer who claims he ban evades using this "Hola VPN". Wikipedia has it blocked, I was hoping there would be a good way to block it here. I guess I'll keep looking.

**Comment by jxsl13** [comment]
Get his IPs and fetch the infos from ipinfo.io as well as the allocated ranges for that VPN provider.

**Comment by LifeIsNull** [comment]
Thanks!
