### ISSUE TITLE
No updates for a long time

### ISSUE THREAD

**Issue by ThEWiZ76** [ejrv/VPNs#15]
So, is this project abandoned or are there any other issues? No updates for a long time makes this list not very useful. Could the author please elaborate? I want to know if I should switch to another provider. Thanks!

**Comment by m-cameron** [comment]
@ThEWiZ76 Any suggestion of alternative provider?

**Comment by ThEWiZ76** [comment]
@m-cameron unfortunately I haven't found something like this yet :(

**Comment by kennell** [comment]
@m-cameron @ThEWiZ76 https://focsec.com for up to date VPN ip address data, it is a paid service but has a free trial

**Comment by ThEWiZ76** [comment]
Thanks the the link!
