### ISSUE TITLE
VPN Unlimited

### ISSUE THREAD

**Issue by ruzzle** [ejrv/VPNs#3]
I don't believe the IP's of VPN unlimited are in your set.

You can find a list of hostnames @ https://hub.docker.com/r/jstewig/docker-vpn-unlimited/

Would be a good addition!

**Comment by ejrv** [comment]
Good catch, thank you! I've just added them, see also https://github.com/ejrv/VPNs/commit/4cff78dec869dd2d7c46840c8daf1334679a0026

Will be in the next bi-monthlyish update. Yell if you find any more hostnames that should be added. :slightly_smiling_face:
